In [1]:
import numpy as np
A = [[1,2,4,17],
    [3,6,-12,3],
    [2,3,-3,2],
    [0,2,-2,6]]
b = [17,3,3,4]
np.linalg.solve(A, b)

array([ 2., -1.,  0.,  1.])

In [8]:
import scipy
from scipy import linalg

A = [[5,1,-1],
    [3,0,1],
    [7,1,-1]]

In [9]:
A_inv = linalg.inv(A)
A_inv

array([[-0.5,  0. ,  0.5],
       [ 5. ,  1. , -4. ],
       [ 1.5,  1. , -1.5]])

In [10]:
linalg.det(A)

2.0

In [11]:
lam, xi = linalg.eig(A)

In [13]:
print("特征值：",lam)
# print("特征向量",xi)

特征值： [ 4.53786058+0.j        -0.26893029+0.6069702j -0.26893029-0.6069702j]


In [12]:
# PA=LU
p_inv, L, U = linalg.lu(A)

In [13]:
print(p_inv)

[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]


In [14]:
print(L)

[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.33333333  0.          1.          0.        ]
 [ 0.66666667 -0.5         0.5         1.        ]]


In [15]:
print(U)

[[  3.   6. -12.   3.]
 [  0.   2.  -2.   6.]
 [  0.   0.   8.  16.]
 [  0.   0.   0.  -5.]]


### 矩阵乘法

In [19]:
import numpy as np
A = np.array([[1,-5], [1,-4],[1,-3], [1,-2],[1,-1], [1,0],
              [1,1] ,[1,2], [1,3], [1,4], [1,5]])
B = A.T.dot(A)
print(A)
print(B)

[[ 1 -5]
 [ 1 -4]
 [ 1 -3]
 [ 1 -2]
 [ 1 -1]
 [ 1  0]
 [ 1  1]
 [ 1  2]
 [ 1  3]
 [ 1  4]
 [ 1  5]]
[[ 11   0]
 [  0 110]]


In [9]:
np.linalg.matrix_rank(B)

2

In [20]:
B_inv = np.linalg.inv(B)
B_inv

array([[0.09090909, 0.        ],
       [0.        , 0.00909091]])

In [21]:
b = np.array([2,7,9,12,13,14,14,13,10,8,4])

In [23]:
w = B_inv.dot(A.T).dot(b)
w

array([9.63636364, 0.18181818])

In [24]:
w.dot(B).dot(w)-2*w.dot(A.T).dot(b)+b.dot(b)

162.90909090909122

In [13]:
import numpy as np
A = np.array([[1,-5,25], [1,-4,16],[1,-3,9], [1,-2,4],[1,-1,1], [1,0,0],
              [1,1,1] ,[1,2,4], [1,3,9], [1,4,16], [1,5,25]])
B = A.T.dot(A)
print(A)
print(B)


[[ 1 -5 25]
 [ 1 -4 16]
 [ 1 -3  9]
 [ 1 -2  4]
 [ 1 -1  1]
 [ 1  0  0]
 [ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]
[[  11    0  110]
 [   0  110    0]
 [ 110    0 1958]]


In [14]:
B_inv = np.linalg.inv(B)
B_inv

array([[ 0.20745921,  0.        , -0.01165501],
       [ 0.        ,  0.00909091,  0.        ],
       [-0.01165501, -0.        ,  0.0011655 ]])

In [15]:
b = np.array([2,7,9,12,13,14,14,13,10,8,4])
C = A.T.dot(b)

In [16]:
C

array([106,  20, 688])

In [17]:
w = B_inv.dot(C)
w

array([13.97202797,  0.18181818, -0.43356643])

In [18]:
w.dot(B).dot(w)-2*w.dot(A.T).dot(b)+b.dot(b)

1.622377622377826